excludes = ["*.lock", ".gitignore"]
on-unmatched = "warn"

[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]

[formatter.mdformat]
command = "mdformat"
includes = ["*.md"]

[formatter.stylua]
command = "stylua"
includes = ["*.lua"]
